version: 0.2

env:
  variables:
    DOCKERHUB_REPO: "sabula/codeaws"
    IMAGE_TAG: "latest"
    DOCKERHUB_USERNAME: "sabula"
    DOCKERHUB_PASSWORD: "Bunnygunnu121!"

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 20
    commands:
      - echo "Installing Trivy..."
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      - mv trivy /usr/local/bin/
      - trivy --version
      - mvn -v

  pre_build:
    commands:
      - echo "Logging into Docker Hub..."
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

  build:
    commands:
      - echo "Compiling and testing with Maven..."
      - mvn clean install -DskipTests=false

      - echo "Running OWASP Dependency-Check..."
      - mvn org.owasp:dependency-check-maven:check

      - echo "Building Docker image..."
      - docker build -t $DOCKERHUB_REPO:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Scanning Docker image with Trivy..."
      - trivy image --exit-code 1 --severity CRITICAL $DOCKERHUB_REPO:$IMAGE_TAG

      - echo "Pushing image to Docker Hub..."
      - docker push $DOCKERHUB_REPO:$IMAGE_TAG

artifacts:
  files:
    - target/*.jar