version: 0.2

env:
  variables:
    DOCKERHUB_REPO: "sabula/codeaws"
    IMAGE_TAG: "latest"
    DOCKERHUB_USERNAME: "sabula"
    DOCKERHUB_PASSWORD: "Bunnygunnu121!"
    NVD_API_KEY       : "2e141ebc-7bec-47c3-bfd9-0881020fcf31"

phases:
  install:
    runtime-versions:
      java: corretto17
    

  pre_build:
    commands:
      - echo "Logging into Docker Hub..."
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

  build:
    commands:
      - echo "Compiling and testing with Maven..."
      - mvn clean install -DskipTests=false
      
      - echo "Clearing OWASP Dependency-Check cache..."
      - mvn org.owasp:dependency-check-maven:purge
      
      - echo "Building Docker image..."
      - docker build -t $DOCKERHUB_REPO:$IMAGE_TAG .
 

      - echo "Running OWASP Dependency-Check..."
      - mvn org.owasp:dependency-check-maven:check
         -DdataMirroringEnabled=false 
         -DfailBuildOnCVSS=11 
         -Dformat=HTML 
         -DoutputDirectory=dependency-check-report
         -DfailOnError=false

     

  post_build:
    commands:
    
      - echo "Pushing image to Docker Hub..."
      - docker push $DOCKERHUB_REPO:$IMAGE_TAG

artifacts:
  files:
    - target/*.jar
    - dependency-check-report/*.html